name: MovieReviewApp CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('movie_review_application/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r movie_review_application/requirements.txt

      - name: Run tests
        run: |
          python movie_review_application/manage.py test

      - name: Build Docker image
        run: |
          docker build -t blagica999/movie-review-app-cicd:latest -f movie_review_application/Dockerfile movie_review_application/

      - name: Push Docker image to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "blagica999" --password-stdin
          docker push blagica999/movie-review-app-cicd:latest

      - name: Notify GitHub on success
        if: success()
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"body":"Build, test, and Docker build and push to DockerHub succeeded"}' \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments

      - name: Notify GitHub on failure
        if: failure()
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"body":"Build, test, or Docker build and push to DockerHub failed"}' \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
